#!/bin/bash -eu

[[ -n ${ROOT-} ]] || exit 0

if [[ ${BUILD_IN_ROOT:-0} == 1 ]]; then
	"$BIN"/rootfs/make modules_install
else
	kernelrelease=$("$BIN"/make -s kernelrelease)
	"$BIN"/make DEPMOD=true INSTALL_MOD_PATH="$ROOT" modules_install
	"$BIN"/rootfs/run depmod -ae -F "$OUTPUT_DIR/System.map" "$kernelrelease"
fi
