#!/bin/bash -eu

"$BIN"/cross preflight-vng "${ROOT-}" "$ARCH"
"$BIN"/vng/min-config "$TMP_DIR"/vng-min.config "$ARCH"
"$BIN"/vng/stop-vm -f
"$BIN"/vng/start-console
ln -sfnT "$TMP_DIR"/vng.ssh "$BUILD_DIR"/ssh
