#!/usr/bin/env bash
set -e

[[ ${COMPILE_COMMANDS:-0} == 1 ]] || exit 0
"$BUILD_DIR/scripts/clang-tools/gen_compile_commands.py" \
	-d "$OUTPUT_DIR" -o "$OUTPUT_DIR/compile_commands.json"
if [[ ! "$BUILD_DIR" -ef "$OUTPUT_DIR" ]]; then
	ln -sfnT "$(realpath -- "$OUTPUT_DIR/compile_commands.json")" \
		"$BUILD_DIR/compile_commands.json"
fi
