#!/bin/bash -eu

SCRIPT_DIR=$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")

# shellcheck disable=SC1091
source "$SCRIPT_DIR/../bin/env.sh"

if [[ ${ROOT-} == 0 ]]; then
	unset ROOT
elif [[ -n ${ROOT-} ]]; then
	resolve_root || exit 1
fi

"$BIN"/write-env

rm -f -- "$TMP_DIR"/*min.config
: >"$TMP_DIR"/min.config

ln -sfnT "$TMP_DIR" "$BUILD_DIR"/tmp-"$VNG_PORT"
