#!/bin/bash -eu

SCRIPT_DIR=$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")

# shellcheck disable=SC1091
source "$SCRIPT_DIR/../bin/env.sh"

if [[ ${ROOT-} == 0 ]]; then
	unset ROOT
elif [[ -n ${ROOT-} ]]; then
	resolve_root || exit 1
fi

env_file=$TMP_DIR/env.sh
{
	printf '#!/bin/bash\n'
	for key in \
		TOOLS_DIR BUILD_DIR BUILD_OPTIONS ROOT AUTO_INSTALL_DEPS BUILD_IN_ROOT \
		ARCH CROSS_COMPILE BUILD_TARGET VNG_DIR VNG_PORT VNG_MEM TMP_DIR OUTPUT_DIR
	do
		if [[ -n ${!key-} ]]; then
			printf 'export %s=%q\n' "$key" "${!key}"
		else
			printf 'unset %s\n' "$key"
		fi
	done
} >"$env_file"

rm -f -- "$TMP_DIR"/*min.config
: >"$TMP_DIR"/min.config

ln -sfnT "$TMP_DIR" "$BUILD_DIR"/tmp-"$VNG_PORT"
