#!/usr/bin/env bash

VERSION=${VERSION-}
PATCHLEVEL=${PATCHLEVEL-}

"$BIN"/cross suse-arch "${ARCH-}" >/dev/null

OUTPUT="$TMP_DIR"/min.config
touch "$OUTPUT"

if [[ -n $VERSION || -n $PATCHLEVEL ]]; then
	if [[ -z $VERSION || -z $PATCHLEVEL ]]; then
		echo "ERROR: VERSION and PATCHLEVEL must be set together" >&2
		exit 1
	fi

	"$BUILD_DIR"/scripts/config \
		--file "$OUTPUT" \
		--enable SUSE_PRODUCT_SLE \
		--set-val SUSE_VERSION "$VERSION" \
		--set-val SUSE_PATCHLEVEL "$PATCHLEVEL" \
		--disable SUSE_KERNEL_SUPPORTED \
		--disable SUSE_HAVE_STABLE_KABI
else
	"$BUILD_DIR"/scripts/config \
		--file "$OUTPUT" \
		--enable SUSE_PRODUCT_OPENSUSE_TUMBLEWEED
fi

"$BUILD_DIR"/scripts/config --file "$OUTPUT" --set-str MODULE_SIG_KEY "certs/signing_key.pem"
