DEFAULTS OVERRIDE IF DEFINED PROFILE_BUILD_TYPE
BUILD_TYPE = ${PROFILE_BUILD_TYPE}

DEFAULTS OVERRIDE IF DEFINED PROFILE_ADD_CONFIG
ADD_CONFIG = ${PROFILE_ADD_CONFIG}

DEFAULTS OVERRIDE IF DEFINED PROFILE_CLEAR_ADD_CONFIG
ADD_CONFIG =

DEFAULTS OVERRIDE IF DEFINED PROFILE_VERSION
VERSION = ${PROFILE_VERSION}

DEFAULTS OVERRIDE IF DEFINED PROFILE_PATCHLEVEL
PATCHLEVEL = ${PROFILE_PATCHLEVEL}

DEFAULTS OVERRIDE IF DEFINED PROFILE_SUSE
PRE_KTEST_PROFILE = VERSION=${VERSION} PATCHLEVEL=${PATCHLEVEL} ${RUN} ${THIS_DIR}/hooks/suse/pre_ktest
