DEFAULTS

INCLUDE ../setup.conf

CONFIG_DIR := ${THIS_DIR}/config

TOOLS_DIR := ${THIS_DIR}/tools
ENV := ${ENV} TOOLS_DIR=${TOOLS_DIR}

BUILD_DIR = ${PWD}
ENV := ${ENV} BUILD_DIR=${BUILD_DIR}

BUILD_OPTIONS := ${shell echo -j$(nproc)}
ENV := ${ENV} BUILD_OPTIONS=${BUILD_OPTIONS}

DEFAULTS IF NOT DEFINED CC
CC =

DEFAULTS
ENV := ${ENV} CC=${CC}

LOCALVERSION = -kt
STORE_FAILURES = ${TMP_DIR}/failures
STORE_SUCCESSES = ${TMP_DIR}/successes
LOG_FILE = ${TMP_DIR}/kt.log
CLEAR_LOG = 1

PRE_KTEST_CHAIN := ${SETENV} ${THIS_DIR}/hooks/pre_ktest
PRE_BUILD_CHAIN := DEPS="awk bc binutils bison busybox diff flex gcc grep iproute2 libdw libelf libssl make rsync ssh tar vim util-linux ${DEPS}" ${RUN} ${THIS_DIR}/hooks/pre_build
POST_BUILD_CHAIN := ${RUN} ${THIS_DIR}/hooks/post_build
PRE_INSTALL_CHAIN := ${RUN} ${THIS_DIR}/hooks/pre_install
POST_INSTALL_CHAIN := ${RUN} ${THIS_DIR}/hooks/post_install
PRE_TEST_CHAIN := ${RUN} ${THIS_DIR}/hooks/pre_test
POST_TEST_CHAIN := ${RUN} ${THIS_DIR}/hooks/post_test
POST_KTEST_CHAIN := ${RUN} ${THIS_DIR}/hooks/post_ktest

# TEST SPECIFIC HOOKS
PRE_KTEST_APPEND = true
PRE_BUILD_APPEND = true
POST_BUILD_APPEND = true
PRE_INSTALL_APPEND = true
POST_INSTALL_APPEND = true
PRE_TEST_APPEND = true
POST_TEST_APPEND = true
POST_KTEST_APPEND = true
