DEFAULTS IF NOT DEFINED ARCH
ARCH := ${shell ${THIS_DIR}/bin/cross resolve-arch "${ROOT}"}

DEFAULTS IF NOT DEFINED CROSS_COMPILE
CROSS_COMPILE := ${shell ${THIS_DIR}/bin/cross cross-compile "${ARCH}"}

KLAB_BUILD_TARGET := ${shell ${THIS_DIR}/bin/cross build-target "${ARCH}"}

DEFAULTS IF NOT DEFINED BUILD_TARGET
BUILD_TARGET = ${KLAB_BUILD_TARGET}

DEFAULTS OVERRIDE

ENV := ${ENV} ARCH="${ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" BUILD_TARGET="${KLAB_BUILD_TARGET}"
