DEFAULTS IF NOT DEFINED ARCH
ARCH := ${shell uname -m}

DEFAULTS
KLAB_ARCH := ${shell ${THIS_DIR}/bin/cross normalize-arch "${ARCH}"}
KLAB_UNAME_ARCH := ${shell ${THIS_DIR}/bin/cross uname-arch "${ARCH}"}

DEFAULTS IF NOT DEFINED CROSS_COMPILE
CROSS_COMPILE = ${shell ${THIS_DIR}/bin/cross cross-compile "${ARCH}"}

DEFAULTS IF NOT DEFINED CHROOT
CHROOT =

DEFAULTS IF NOT DEFINED BUILD_TARGET
BUILD_TARGET = ${shell ${THIS_DIR}/bin/cross build-target "${ARCH}"}

DEFAULTS
