INCLUDE base.conf
INCLUDE patterns.conf
INCLUDE rootfs.conf
INCLUDE cross.conf

DEFAULTS IF DEFINED OPENSUSE || (DEFINED SUSE_VERSION && DEFINED SUSE_PATCHLEVEL)
INCLUDE suse.conf

DEFAULTS
INCLUDE vng.conf
INCLUDE setenv.conf
