DEFAULTS IF NOT DEFINED TEST_BIN
TEST_BIN = sleep infinity

DEFAULTS IF NOT DEFINED TEST
TEST := default

DEFAULTS IF NOT DEFINED PROFILE
PROFILE := default

DEFAULTS

INCLUDE base.conf
INCLUDE patterns.conf
INCLUDE rootfs.conf
INCLUDE cross.conf
INCLUDE suse.conf
INCLUDE vng.conf
INCLUDE setenv.conf
INCLUDE apply-profile.conf

DEFAULTS

TEST_START IF ${TEST} == default
TEST_TYPE = test
TEST = ${DO_TEST_SIMPLE}
