INCLUDE base.conf
INCLUDE patterns.conf
INCLUDE rootfs.conf
INCLUDE cross.conf

DEFAULTS IF DEFINED OPENSUSE || (DEFINED SUSE_VERSION && DEFINED SUSE_PATCHLEVEL)
INCLUDE suse.conf

DEFAULTS
INCLUDE vng.conf
INCLUDE setenv.conf

DEFAULTS IF NOT DEFINED TEST_BIN
TEST_BIN = sleep infinity

DEFAULTS IF NOT DEFINED TEST
TEST := defconfig

TEST_START IF ${TEST} == defconfig
TEST_TYPE = test
TEST = ${DO_TEST_SIMPLE}
BUILD_TYPE = defconfig
