DEFAULTS OVERRIDE

DEFAULTS IF NOT DEFINED MACHINE
MACHINE = ${ARCH}_builder

TMP_DIR = ${THIS_DIR}/tmp/${MACHINE}
ENV := ${ENV} TMP_DIR=${TMP_DIR}

OUTPUT_DIR = ${TMP_DIR}/build
ENV := ${ENV} OUTPUT_DIR=${OUTPUT_DIR}

MIN_CONFIG = ${TMP_DIR}/min.config
STORE_FAILURES = ${TMP_DIR}/failures
STORE_SUCCESSES = ${TMP_DIR}/successes
LOG_FILE = ${TMP_DIR}/kt.log
CLEAR_LOG = 1
