DEFAULTS IF NOT DEFINED ROOT
ROOT =

DEFAULTS IF NOT DEFINED AUTO_INSTALL_DEPS
AUTO_INSTALL_DEPS = 0

DEFAULTS OVERRIDE

ENV := ${ENV} ROOT="${ROOT}"
ENV := ${ENV} AUTO_INSTALL_DEPS=${AUTO_INSTALL_DEPS}

DEPS := ${DEPS} bc binutils bison dwarves flex gcc gxx libcap libdw libdwarf libelf libssl make python-docutils rsync tar
INSTALL_DEPS = ${DEPS}

PRE_TEST_CHAIN := ${PRE_TEST_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/rootfs/pre_test
POST_BUILD_CHAIN := ${POST_BUILD_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/rootfs/post_build
POST_TEST_CHAIN := ${POST_TEST_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/rootfs/post_test
POST_KTEST_CHAIN := ${POST_KTEST_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/rootfs/post_ktest
