DEFAULTS IF NOT DEFINED ROOT
ROOT := 0

DEFAULTS IF NOT DEFINED AUTO_INSTALL_DEPS
AUTO_INSTALL_DEPS = 1

DEFAULTS IF NOT DEFINED BUILD_IN_ROOT
BUILD_IN_ROOT = 0

DEFAULTS OVERRIDE

ENV := ${ENV} ROOT="${ROOT}"
ENV := ${ENV} AUTO_INSTALL_DEPS=${AUTO_INSTALL_DEPS}
ENV := ${ENV} BUILD_IN_ROOT=${BUILD_IN_ROOT}

PRE_TEST_CHAIN := ${PRE_TEST_CHAIN} && ${RUN} ${THIS_DIR}/hooks/rootfs/pre-test
PRE_KTEST_CHAIN := ${PRE_KTEST_CHAIN} && ${RUN} ${THIS_DIR}/hooks/rootfs/pre-ktest
POST_BUILD_CHAIN := ${POST_BUILD_CHAIN} && ${RUN} ${THIS_DIR}/hooks/rootfs/post-build
POST_TEST_CHAIN := ${POST_TEST_CHAIN} && ${RUN} ${THIS_DIR}/hooks/rootfs/post-test
POST_KTEST_CHAIN := ${POST_KTEST_CHAIN} && ${RUN} ${THIS_DIR}/hooks/rootfs/post-ktest
