DEFAULTS OVERRIDE
TEST_TYPE = test
TEST_DIR = ${OUTPUT_DIR}/kselftest/kselftest_install/bpf
TEST_BIN = ./test_progs
TEST = ${SSH} sh -c 'mount bpffs /sys/fs/bpf -t bpf && cd ${TEST_DIR} && ${TEST_BIN}'
POST_BUILD_APPEND = ${RUN} ${THIS_DIR}/hooks/selftests/post-build bpf
ADD_CONFIG = ${BUILD_DIR}/tools/testing/selftests/bpf/config ${BUILD_DIR}/tools/testing/selftests/bpf/config.${KLAB_ARCH}
