BUILD_ENV = BIN="${THIS_DIR}/bin" BUILD_DIR="${BUILD_DIR}" OUTPUT_DIR="${OUTPUT_DIR}" TMP_DIR="${TMP_DIR}" ARCH="${KLAB_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" CHROOT="${CHROOT}" CHROOT_BUILD="${CHROOT_BUILD}" CC="${CC}" HOSTCC="${HOSTCC}" HOSTCFLAGS="${HOSTCFLAGS}" COMPILE_COMMANDS="${COMPILE_COMMANDS}" BUILD_OPTIONS="${BUILD_OPTIONS}"
VNG_ENV = VNG="${VNG}" BUSYBOX="${BUSYBOX}" VNG_PORT="${VNG_PORT}" VNG_MEM="${VNG_MEM}" VNG_ROOT_DEV="${VNG_ROOT_DEV}" VNG_ROOT_FSTYPE="${VNG_ROOT_FSTYPE}" ROOT_DISK="${ROOT_DISK}"
RUN = env ${BUILD_ENV} ${VNG_ENV}

DEFAULTS OVERRIDE
MAKE_CMD = ${RUN} ${THIS_DIR}/bin/make

PRE_KTEST = ${PRE_KTEST_CHAIN} && ${PRE_KTEST_APPEND}
PRE_KTEST_DIE = 1
PRE_BUILD = ${PRE_BUILD_CHAIN} && ${PRE_BUILD_APPEND}
PRE_BUILD_DIE = 1
POST_BUILD = ${POST_BUILD_CHAIN} && ${POST_BUILD_APPEND}
POST_BUILD_DIE = 1
PRE_INSTALL = ${PRE_INSTALL_CHAIN} && ${PRE_INSTALL_APPEND}
POST_INSTALL = ${POST_INSTALL_CHAIN} && ${POST_INSTALL_APPEND}
PRE_TEST = ${PRE_TEST_CHAIN} && ${PRE_TEST_APPEND}
PRE_TEST_DIE = 1
POST_TEST = ${POST_TEST_CHAIN} && ${POST_TEST_APPEND}
POST_KTEST = ${POST_KTEST_CHAIN} && ${POST_KTEST_APPEND}
