SETENV = env ${ENV}
RUN = TMP_DIR=${TMP_DIR} ${THIS_DIR}/bin/run

DEFAULTS OVERRIDE
MAKE_CMD = ${RUN} ${THIS_DIR}/bin/make

PRE_KTEST = ${PRE_KTEST_CHAIN} && ${PRE_KTEST_PROFILE} && ${PRE_KTEST_APPEND} && ${RUN} ${THIS_DIR}/bin/cat-min-config
PRE_KTEST_DIE = 1
PRE_BUILD = ${PRE_BUILD_CHAIN} && ${PRE_BUILD_APPEND}
PRE_BUILD_DIE = 1
POST_BUILD = ${POST_BUILD_CHAIN} && ${POST_BUILD_APPEND}
POST_BUILD_DIE = 1
PRE_INSTALL = ${PRE_INSTALL_CHAIN} && ${PRE_INSTALL_APPEND}
POST_INSTALL = ${POST_INSTALL_CHAIN} && ${POST_INSTALL_APPEND}
PRE_TEST = ${PRE_TEST_CHAIN} && ${PRE_TEST_APPEND}
PRE_TEST_DIE = 1
POST_TEST = ${POST_TEST_CHAIN} && ${POST_TEST_APPEND}
POST_KTEST = ${POST_KTEST_CHAIN} && ${POST_KTEST_APPEND}
