KSOURCE_GIT := /linux/kernel-source
MIN_CONFIGS := ${MIN_CONFIGS} ${TMP_DIR}/suse-min.config

PRE_KTEST_CHAIN := ${PRE_KTEST_CHAIN} && SUSE_VERSION=${SUSE_VERSION} SUSE_PATCHLEVEL=${SUSE_PATCHLEVEL} ${RUN_HOOK} ${THIS_DIR}/hooks/suse/pre_ktest
