DEFAULTS IF NOT DEFINED VERSION
VERSION =

DEFAULTS IF NOT DEFINED PATCHLEVEL
PATCHLEVEL =

DEFAULTS IF NOT DEFINED FLAVOR
FLAVOR = default

DEFAULTS
KSOURCE_ARCH := ${shell ${THIS_DIR}/bin/cross suse-arch "${ARCH}"}

DEFAULTS OVERRIDE
BUILD_TYPE = useconfig:${KSOURCE_GIT}/${BRANCH}/config/${KSOURCE_ARCH}/default
ADD_CONFIG = ${KSOURCE_GIT}/${BRANCH}/config/${KSOURCE_ARCH}/${FLAVOR}
PRE_KTEST_APPEND = VERSION="${VERSION}" PATCHLEVEL="${PATCHLEVEL}" ${RUN} ${THIS_DIR}/hooks/suse/pre-ktest
