INCLUDE base.conf
INCLUDE patterns.conf
INCLUDE rootfs.conf
INCLUDE cross.conf
INCLUDE vng.conf

KSOURCE_GIT := /linux/kernel-source
MIN_CONFIGS := ${MIN_CONFIGS} ${TMP_DIR}/suse-min.config

PRE_BUILD_CHAIN := ${PRE_BUILD_CHAIN} && SUSE_VERSION=${SUSE_VERSION} SUSE_PATCHLEVEL=${SUSE_PATCHLEVEL} ${RUN_HOOK} ${THIS_DIR}/hooks/suse/pre_build

INCLUDE setenv.conf
