VNG_DIR := ${TOOLS_DIR}/virtme-ng
ENV := ${ENV} VNG_DIR=${VNG_DIR}

DEFAULTS IF NOT DEFINED VNG_PORT
VNG_PORT := 22000

DEFAULTS IF NOT DEFINED VNG_MEM
VNG_MEM = 1G

DEFAULTS OVERRIDE

ENV := ${ENV} VNG_PORT=${VNG_PORT}
ENV := ${ENV} VNG_MEM=${VNG_MEM}

MACHINE = vng_${VNG_PORT}
LOCALVERSION = -${MACHINE}

TMP_DIR = ${THIS_DIR}/tmp/${MACHINE}
ENV := ${ENV} TMP_DIR=${TMP_DIR}

OUTPUT_DIR = ${TMP_DIR}/build
ENV := ${ENV} OUTPUT_DIR=${OUTPUT_DIR}

MIN_CONFIG = ${TMP_DIR}/min.config

CONSOLE = cat ${THIS_DIR}/tmp/${MACHINE}/console
SUCCESS_LINE = virtme(-ng)?-init: starting script

SSH_USER = ${shell whoami}
SSH = ${RUN} ${THIS_DIR}/bin/vng/cmd --ssh-tcp --ssh-client ${VNG_PORT} --
SSH_EXEC = ${SSH} $SSH_COMMAND

# umount rootfs, if any, so the host does not leak into vm
VNG_PRE_START = ${RUN} ${THIS_DIR}/bin/rootfs/umount

POWER_CYCLE = ${RUN} ${THIS_DIR}/bin/vng/stop-vm && ${VNG_PRE_START} && ${RUN} ${THIS_DIR}/bin/vng/start-vm ${VNG_ARGS}
POWER_OFF = ${RUN} ${THIS_DIR}/bin/vng/stop-vm -f

REBOOT_ON_SUCCESS = 0
REBOOT_ON_ERROR = 0
REBOOT_TYPE = script
REBOOT = ${POWER_CYCLE}
REBOOT_RETURN_CODE = 0
REBOOT_SUCCESS_LINE = ${SUCCESS_LINE}

# ktest.pl still dereferences TARGET_IMAGE during dry-run even though the vng
# flow never installs a kernel onto a guest filesystem path.
TARGET_IMAGE = /boot/vmlinuz-test
NO_INSTALL = 1

PRE_KTEST_CHAIN := ${PRE_KTEST_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/vng/pre_ktest
PRE_BUILD_CHAIN := ${PRE_BUILD_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/vng/pre_build
POST_BUILD_CHAIN := ${POST_BUILD_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/vng/post_build
POST_KTEST_CHAIN := ${POST_KTEST_CHAIN} && ${RUN_HOOK} ${THIS_DIR}/hooks/vng/post_ktest
